### ISSUE TITLE
桑基图没有被正确展示

### ISSUE THREAD

**Issue by CharlesTHN** [running-elephant/datart-extension-charts#21]
**Describe the bug**
我把 experiment-antv-sankey.js 复制到自己的项目下，F12查看已经成功加载到，但是图表中并没有这个图

![image](https://user-images.githubusercontent.com/19632429/219321811-35f7b714-c57a-4581-8158-925685ee1fd9.png)

**Comment by Cuiyansong** [comment]
如果console里面没有报错的话，请重新登录系统，再新建图表试试

**Comment by CharlesTHN** [comment]
![image](https://user-images.githubusercontent.com/19632429/219339299-42e96dea-5050-4321-94a4-705c8d6419cc.png)
哦哦，console报错了

**Comment by Cuiyansong** [comment]
什么浏览器以及浏览器版本？

**Comment by CharlesTHN** [comment]
Google Chrome
版本 109.0.5414.119（正式版本） (arm64)

**Comment by Cuiyansong** [comment]
Datart版本呢？

**Comment by CharlesTHN** [comment]
1.0.0-rc.1

**Comment by Cuiyansong** [comment]
这个报错信息很难分辨出问题，我目前用的是Dev分支代码，是没有报错的。
你把报错信息帖的更详细一些

**Comment by CharlesTHN** [comment]
那我本地用dev试一试

**Comment by Cuiyansong** [comment]
可以从[Github Datart](https://github.com/running-elephant/datart)主页加入社区群，这样沟通可能会更便捷一些。

**Comment by CharlesTHN** [comment]
我用dev也不行，
![image](https://user-images.githubusercontent.com/19632429/219537307-774d36cd-3b1d-42eb-b8a0-4a3d018544f5.png)

我在社区群，那我在群里问一下
