### ISSUE TITLE
有两种选择颜色的组件，但其中一种的配置可能是有问题？

### ISSUE THREAD

**Issue by hexawing** [running-elephant/datart-extension-charts#25]
**Describe the bug**
首先这可能不是个bug，但我找了文档也没有找到如何处理，只好在这里问一下了。

**To Reproduce**
使用任意官方自带组件，往“颜色”一栏中拖入一项文本的数据，再编辑其“着色”，大致会是这样的结果：
![image](https://user-images.githubusercontent.com/230037/223062229-4e81590e-edf0-4cf4-9829-161738ba825d.png)

我自己写自定义组件，代码如果写成这样：
```javascript
{
  label: 'colorize',
  key: 'colorize',
  type: 'colorize',
  action: {STRING: ['colorize']}
}
```
在前端显示的效果是这样的：
![image](https://user-images.githubusercontent.com/230037/223062812-b17a7918-4f39-4ae3-95c0-eaea05946176.png)

倒是也能弹出右边“选择主题”里面的那些主题，但左边这个只显示一行undefined

如果我代码写成另外一种：
```javascript
{
  label: 'colorize',
  key: 'colorize',
  type: 'colorize',
  action: {STRING: ['colorRange']}
}
```
在前端的显示就成了这样：
![image](https://user-images.githubusercontent.com/230037/223063536-16ccccbb-0f88-4859-8d86-fa5794a120e5.png)
显然也不对

**Expected behavior**
多半是我哪里配置得不对，但我找了文档，似乎也没有更深层的说明。

**Screenshots**
如上

**Desktop (please complete the following information):**
 - OS: Win 7 / Win 10
 - Browser Chrome / Edge
 - Version Chrome 已是最新版本版本 110.0.5481.178（正式版本） （64 位）/Microsoft Edge 版本 111.0.1660.14 (正式版本) dev (64 位)

**Comment by Cuiyansong** [comment]
可能是当前字段不是STRING字符串类型，而是“数字”类型，可以尝试在“视图”上更改当前字段的类型。
另外，此问题不是插件问题，请不要乱提issue

**Comment by hexawing** [comment]
> 可能是当前字段不是STRING字符串类型，而是“数字”类型，可以尝试在“视图”上更改当前字段的类型。 另外，此问题不是插件问题，请不要乱提issue

抱歉，我有点病急乱投医了。还请指点一下此类问题应该去哪里找答案……
您说的那个原因我试过了，如果两者不匹配，甚至都不会有弹出的菜单，所以应该是别的问题。我再研究一下吧，谢谢了

**Comment by Cuiyansong** [comment]
> {
  label: 'colorize',
  key: 'colorize',
  type: 'colorize',
  action: {STRING: ['colorize']}
}

这里的`type`不是colorize，可以用color或者group试试，参照代码中的`ChartDataSectionType`枚举类型
@hexawing

**Comment by hexawing** [comment]
> > {
> > label: 'colorize',
> > key: 'colorize',
> > type: 'colorize',
> > action: {STRING: ['colorize']}
> > }
> 
> 这里的`type`不是colorize，可以用color或者group试试，参照代码中的`ChartDataSectionType`枚举类型 @hexawing

我傻了，后来我发现它必须要依托别的栏里的字段才能生效，比如维度或者信息里有内容才能取出来
